---

- name: add enpass apt key
  apt_key:
    url: "{{ enpass_apt_key }}"

- name: add enpass repo
  apt_repository:
    repo: "{{ enpass_repo }}"
    state: present
    filename: enpass

- name: install latest enpass
  apt:
    name: enpass
    force_apt_get: true

...
