---

- name: Install neovim apt packages
  ansible.builtin.apt:
    name: "{{ neovim_apt_packages }}"
    state: present
    force_apt_get: true


- block:
    - name: Clone lazyvim starter git repo
      ansible.builtin.git:
        repo: "{{ neovim_lazyvim_starter_url }}"
        dest: "~{{ local_username }}/.config/nvim"
  become: true
  become_user: "{{ local_username }}"

...
